//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReSharperPlugin.ReSharperGamificationPlugin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReSharperPlugin.ReSharperGamificationPlugin.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} characters.
        /// </summary>
        internal static string AutocompleteAchievementGoal_Text {
            get {
                return ResourceManager.GetString("AutocompleteAchievementGoal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocomplete.
        /// </summary>
        internal static string AutocompleteAchievementShort_Text {
            get {
                return ResourceManager.GetString("AutocompleteAchievementShort_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear achievements.
        /// </summary>
        internal static string ClearAchievementsActionText {
            get {
                return ResourceManager.GetString("ClearAchievementsActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} formatting.
        /// </summary>
        internal static string FormattingAchievementGoal_Text {
            get {
                return ResourceManager.GetString("FormattingAchievementGoal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting.
        /// </summary>
        internal static string FormattingAchievementShort_Text {
            get {
                return ResourceManager.GetString("FormattingAchievementShort_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamification.
        /// </summary>
        internal static string GamificationActionGroupText {
            get {
                return ResourceManager.GetString("GamificationActionGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% refactorings.
        /// </summary>
        internal static string RefactoringAchievementGoal_Text {
            get {
                return ResourceManager.GetString("RefactoringAchievementGoal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactoring.
        /// </summary>
        internal static string RefactoringAchievementShort_Text {
            get {
                return ResourceManager.GetString("RefactoringAchievementShort_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset usage counters.
        /// </summary>
        internal static string ResetActivityCountersActionText {
            get {
                return ResourceManager.GetString("ResetActivityCountersActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show achievements.
        /// </summary>
        internal static string ShowAchievements_Text {
            get {
                return ResourceManager.GetString("ShowAchievements_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You achieved {0} in {1}!.
        /// </summary>
        internal static string YouMadeAnAchievement_Text {
            get {
                return ResourceManager.GetString("YouMadeAnAchievement_Text", resourceCulture);
            }
        }
    }
}
