<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>ReSharperPlugin.ReSharperGamificationPlugin</AssemblyName>
    <RootNamespace>$(AssemblyName)</RootNamespace>
    <IsPackable>false</IsPackable>
    <DefineConstants>$(DefineConstants);RIDER</DefineConstants>
    <UseWpf>True</UseWpf>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.HabitatDetector" Version="1.4.3" />
    <PackageReference Include="JetBrains.Lifetimes" Version="2024.3.0" />
    <PackageReference Include="JetBrains.ReSharper.SDK" Version="251.0.20241213-eap01d">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="JetBrains.ReSharper.SDK.Tests" Version="251.0.20241213-eap01d">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="JetBrains.Rider.SDK" Version="251.0.20241213-eap01d">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="JetBrains.Rider.SDK.Tests" Version="251.0.20241213-eap01d">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="SqlServer.Dac" Version="12.0.0" />
  </ItemGroup>

</Project>
